site_name: Joel's BotC in Minecraft Docs
site_url: https://botc.joel4848.com
theme:
  name: material
  palette:
    - scheme: homepage

  custom_dir: docs/overrides

  # logo: assets/logo.png

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - header.autohide
  
markdown_extensions:
    - attr_list
    - md_in_html
    - pymdownx.blocks.caption

extra_css:
  - stylesheets/extra.css


# home_tagline: Shadow Wizards Only
# home_description: |
#   This site is an example showcase for my "mkdocs-coverpage" repository.

# Custom Homepage Button(s)
home_button1_name: Documentation                 # Comment this parameter out to remove the button.
home_button1_url: documentation/                       # This path starts at your root mkdocs directory.
home_button1_theme: md-button--primary           # Options: "md-button", "md-button md-button--primary"
home_button1_icon: people                        # Options: "people", "gear", "image"
home_button1_blurb: |                            # Short description of this button / section.
  Documentation for setting up and running Joel4848's BotC map & datapack

home_button2_name: Issues & Feedback   # Comment this parameter out to remove the button.
home_button2_url: https://github.com/joel4848/BotC-Minecraft/issues    # This path starts at your root mkdocs directory.
home_button2_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button2_icon: gear       # Options: "people", "gear", "image"
home_button2_blurb: |         # Short description of this button / section.
  Please click here to report and issues or give feedback via the Github repo

home_button3_name: Custom Maps   # Comment this parameter out to remove the button.
home_button3_url: Folder3/    # This path starts at your root mkdocs directory.
home_button3_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button3_icon: image      # Options: "people", "gear", "image"
home_button3_blurb: |         # Short description of this button / section.
  Documentation on setting up and running the datapack on your own map