site_name: Joel's BotC in Minecraft Docs
site_url: https://joel4848.github.io/BotC-Minecraft
theme:
  name: material
  palette:
    - scheme: homepage

  custom_dir: docs/overrides

  # logo: assets/logo.png

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - header.autohide
  
markdown_extensions:
    - attr_list
    - md_in_html
    - pymdownx.blocks.caption

extra_css:
  - stylesheets/extra.css


# home_tagline: Shadow Wizards Only
# home_description: |
#   This site is an example showcase for my "mkdocs-coverpage" repository.

# Custom Homepage Button(s)
# home_button1_name: Main Clicky                   # Comment this parameter out to remove the button.
# home_button1_url: Folder1/                       # This path starts at your root mkdocs directory.
# home_button1_theme: md-button--primary # Options: "md-button", "md-button md-button--primary"
# home_button1_icon: people                        # Options: "people", "gear", "image"
# home_button1_blurb: |                            # Short description of this button / section.
#   This joker navigates to the shadow wizard armory located in "/Folder1/index.md"

# home_button2_name: Clicky 2   # Comment this parameter out to remove the button.
# home_button2_url: Folder2/    # This path starts at your root mkdocs directory.
# home_button2_theme: md-button # Options: "md-button", "md-button md-button--primary"
# home_button2_icon: gear       # Options: "people", "gear", "image"
# home_button2_blurb: |         # Short description of this button / section.
#   This goober navigates to some important thingies located in "/Folder2/index.md"

# home_button3_name: Clicky 3   # Comment this parameter out to remove the button.
# home_button3_url: Folder3/    # This path starts at your root mkdocs directory.
# home_button3_theme: md-button # Options: "md-button", "md-button md-button--primary"
# home_button3_icon: image      # Options: "people", "gear", "image"
# home_button3_blurb: |         # Short description of this button / section.
#   This psycho navigates to an interesting table of stuff located in "/Folder3/index.md"